-- CREATE DATABASE `qrcheck` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

-- -- qrcheck.qr_sessions definition

-- CREATE TABLE `qr_sessions` (
--   `id` int NOT NULL AUTO_INCREMENT,
--   `teacher_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
--   `subject_code` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
--   `subject_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
--   `teacher_code` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   `class_group` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
--   `year` int NOT NULL,
--   `semester` int DEFAULT '1',
--   `start_time` datetime NOT NULL,
--   `late_minute` int DEFAULT '15',
--   `expire_time` datetime NOT NULL,
--   `qr_token` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
--   `qr_code_image` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
--   `is_active` tinyint(1) DEFAULT '1',
--   `description` text COLLATE utf8mb4_unicode_ci,
--   `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
--   `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
--   PRIMARY KEY (`id`),
--   UNIQUE KEY `qr_token` (`qr_token`),
--   KEY `teacher_id` (`teacher_id`),
--   CONSTRAINT `qr_sessions_ibfk_1` FOREIGN KEY (`teacher_id`) REFERENCES `teachers` (`id`) ON DELETE CASCADE
-- ) ENGINE=InnoDB AUTO_INCREMENT=60 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -- qrcheck.student_attendance definition

-- CREATE TABLE `student_attendance` (
--   `id` int NOT NULL AUTO_INCREMENT,
--   `qr_session_id` int NOT NULL,
--   `student_id` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
--   `checkin_time` datetime NOT NULL,
--   `status` enum('มา','สาย','ขาด') COLLATE utf8mb4_unicode_ci NOT NULL,
--   `extra_score` int DEFAULT '0',
--   `notes` text COLLATE utf8mb4_unicode_ci,
--   `ip_address` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   `user_agent` text COLLATE utf8mb4_unicode_ci,
--   `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
--   `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
--   PRIMARY KEY (`id`),
--   UNIQUE KEY `unique_student_session` (`qr_session_id`,`student_id`),
--   KEY `student_id` (`student_id`),
--   CONSTRAINT `student_attendance_ibfk_1` FOREIGN KEY (`qr_session_id`) REFERENCES `qr_sessions` (`id`) ON DELETE CASCADE,
--   CONSTRAINT `student_attendance_ibfk_2` FOREIGN KEY (`student_id`) REFERENCES `students` (`id`) ON DELETE CASCADE
-- ) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -- qrcheck.student_submissions definition

-- CREATE TABLE `student_submissions` (
--   `id` int NOT NULL AUTO_INCREMENT,
--   `student_id` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
--   `teacher_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
--   `qr_session_id` int NOT NULL,
--   `submission_time` datetime NOT NULL,
--   `firstname` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
--   `lastname` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
--   `ip_address` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
--   PRIMARY KEY (`id`),
--   KEY `student_id` (`student_id`),
--   KEY `teacher_id` (`teacher_id`),
--   KEY `qr_session_id` (`qr_session_id`),
--   CONSTRAINT `student_submissions_ibfk_1` FOREIGN KEY (`student_id`) REFERENCES `students` (`id`) ON DELETE CASCADE,
--   CONSTRAINT `student_submissions_ibfk_2` FOREIGN KEY (`teacher_id`) REFERENCES `teachers` (`id`) ON DELETE CASCADE,
--   CONSTRAINT `student_submissions_ibfk_3` FOREIGN KEY (`qr_session_id`) REFERENCES `qr_sessions` (`id`) ON DELETE CASCADE
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- -- qrcheck.students definition

-- CREATE TABLE `students` (
--   `id` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
--   `firstname` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
--   `lastname` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
--   `student_code` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
--   `class_group` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   `year` int DEFAULT NULL,
--   `semester` int DEFAULT '1',
--   `major` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
--   `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
--   PRIMARY KEY (`id`),
--   UNIQUE KEY `student_code` (`student_code`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -- qrcheck.system_settings definition

-- CREATE TABLE `system_settings` (
--   `id` int NOT NULL AUTO_INCREMENT,
--   `setting_key` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
--   `setting_value` text COLLATE utf8mb4_unicode_ci,
--   `description` text COLLATE utf8mb4_unicode_ci,
--   `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
--   `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
--   PRIMARY KEY (`id`),
--   UNIQUE KEY `setting_key` (`setting_key`)
-- ) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -- qrcheck.teachers definition

-- CREATE TABLE `teachers` (
--   `id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
--   `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
--   `email` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
--   `auth0_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
--   `teacher_code` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
--   `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
--   PRIMARY KEY (`id`),
--   UNIQUE KEY `email` (`email`),
--   UNIQUE KEY `auth0_id` (`auth0_id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;